<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.1.1" />
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="ErrorOr" Version="2.1.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ExpenseTrackerApp.Domain\ExpenseTrackerApp.Domain.csproj" />
    </ItemGroup>

</Project>
