services:
  webapi:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    build: !reset null
    volumes:
      - ../../:/app
      - nuget_packages:/root/.nuget/packages
      - nuget_http_cache:/root/.local/share/NuGet/http-cache
      - webapi_obj:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.WebApi/obj
      - webapi_bin:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.WebApi/bin
      - application_obj:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Application/obj
      - application_bin:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Application/bin
      - infrastructure_obj:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Infrastructure/obj
      - infrastructure_bin:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Infrastructure/bin
      - domain_obj:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Domain/obj
      - domain_bin:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Domain/bin
      - contracts_obj:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Contracts/obj
      - contracts_bin:/app/ExpenseTrackerApp/src/ExpenseTrackerApp.Contracts/bin
    working_dir: /app/ExpenseTrackerApp/src/ExpenseTrackerApp.WebApi
    command: dotnet watch run --no-launch-profile
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  nuget_packages:
  nuget_http_cache:
  webapi_obj:
  webapi_bin:
  application_obj:
  application_bin:
  infrastructure_obj:
  infrastructure_bin:
  domain_obj:
  domain_bin:
  contracts_obj:
  contracts_bin:
